(* EBNF grammar for instaparse *)
<INPUT> = RULES | NQUERY | QUERY;


NQUERY = <'query'> NAME;
QUERY = <'match'> CONDITION [<'and'> CONDITION]* <';'>*;

<RULES> = [DISCOUNT | PROMOTION]+
    PROMOTION = <'promotion'> NAME PROMOTIONTYPE <'when'> CONDITION [<'and'> CONDITION]* <';'>;
    DISCOUNT = <'discount'> NAME PERCENT <'when'> CONDITION [<'and'> CONDITION]* <';'>;
    <PERCENT> = NUMBER ;
    PROMOTIONTYPE = STRING ;
    
    <NAME> = STRING ;

    NUMBER = #'[0-9]+' ;
    
    (* <STRING> = #'[A-Za-z][A-Za-z0-9_-]+' ; *)
    <STRING> = #'[A-Za-z][A-Za-z0-9\/\._-]+' ;
    
    CONDITION = FACTTYPE FIELD OPERATOR VALUE ;
    FACTTYPE = 'customer' | 'total' | 'order' ;
    <FIELD> = STRING ;
    OPERATOR = 'is' | '>' | '<' | '=' ;
    <VALUE> = STRING | NUMBER ;
